os:
  - linux
  - osx

language: r

r:
  - 3.2
  - release

warnings_are_errors: true

sudo: required

r_packages:
  - knitr
  - covr
  - ggplot2

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Rscript -e 'library(covr); codecov(type = c("tests", "examples"), quiet = FALSE)' Using Wercker CI ; fi

# install sglOptim
before_install:
  - Rscript -e 'install.packages("devtools")'
  - if [[ "$TRAVIS_BRANCH" == "develop" ]]; then Rscript -e 'devtools::install_github("vincent-dk/sglOptim", ref = "develop")' Using Wercker CI ; fi
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then Rscript -e 'devtools::install_github("vincent-dk/sglOptim", ref = "master")' Using Wercker CI ; fi
