-
  branches:
    only:
      - master

  # DO NOT CHANGE the "init" and "install" sections below
  # Download script file from GitHub
  init:
    ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
  install:
    ps: Bootstrap

  # Adapt as necessary starting from here

  environment:
    WARNINGS_ARE_ERRORS: 1
    NOT_CRAN: true

  build_script:
    - travis-tool.sh install_github vincent-dk/sglOptim
    - travis-tool.sh install_deps

  test_script:
    - travis-tool.sh run_tests

  on_failure:
    - 7z a failure.zip *.Rcheck\*
    - appveyor PushArtifact failure.zip

  artifacts:
    - path: '*.Rcheck\**\*.log'
      name: Logs

    - path: '*.Rcheck\**\*.out'
      name: Logs

    - path: '*.Rcheck\**\*.fail'
      name: Logs

    - path: '*.Rcheck\**\*.Rout'
      name: Logs

    - path: '\*_*.tar.gz'
      name: Bits

    - path: '\*_*.zip'
      name: Bits

-
  branches:
    only:
      - develop

  # DO NOT CHANGE the "init" and "install" sections below
  # Download script file from GitHub
  init:
    ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
  install:
    ps: Bootstrap

  environment:
    WARNINGS_ARE_ERRORS: 1
    NOT_CRAN: true

  build_script:
    - travis-tool.sh install_deps
    - travis-tool.sh install_r devtools
    - Rscript -e "devtools::install_github('vincent-dk/sglOptim', ref = 'develop')"

  test_script:
    - travis-tool.sh run_tests

  on_failure:
    - 7z a failure.zip *.Rcheck\*
    - appveyor PushArtifact failure.zip

  artifacts:
    - path: '*.Rcheck\**\*.log'
      name: Logs

    - path: '*.Rcheck\**\*.out'
      name: Logs

    - path: '*.Rcheck\**\*.fail'
      name: Logs

    - path: '*.Rcheck\**\*.Rout'
      name: Logs

    - path: '\*_*.tar.gz'
      name: Bits

    - path: '\*_*.zip'
      name: Bits

-
  branches:
    only:
      - release

  # DO NOT CHANGE the "init" and "install" sections below
  # Download script file from GitHub
  init:
    ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
  install:
    ps: Bootstrap

  environment:
    WARNINGS_ARE_ERRORS: 1
    NOT_CRAN: true

  build_script:
    - travis-tool.sh install_deps
    - travis-tool.sh install_r devtools
    - Rscript -e "devtools::install_github('vincent-dk/sglOptim', ref = 'release')"

  test_script:
    - travis-tool.sh run_tests

  on_failure:
    - 7z a failure.zip *.Rcheck\*
    - appveyor PushArtifact failure.zip

  artifacts:
    - path: '*.Rcheck\**\*.log'
      name: Logs

    - path: '*.Rcheck\**\*.out'
      name: Logs

    - path: '*.Rcheck\**\*.fail'
      name: Logs

    - path: '*.Rcheck\**\*.Rout'
      name: Logs

    - path: '\*_*.tar.gz'
      name: Bits

    - path: '\*_*.zip'
      name: Bits
